### ISSUE TITLE
Should some stylesheets be deleted?

### ISSUE THREAD

**Issue by skube** [kemie/Style-Guide-Boilerplate-Bootstrap-Edition#2]
I'm wondering if the `sg-style.css` and `style.css` sheets should be removed from the project? Do they serve any purpose?

**Comment by kemie** [comment]
No purpose. Removed now. 
(Thanks for reporting bugs, nice to know someone's using this)

**Comment by skube** [comment]
I'm kinda late the Bootstrap party. I can't understand why this kind of thing isn't used more.
