### ISSUE TITLE
Code contained within `Patterns` is nested within an extra column

### ISSUE THREAD

**Issue by skube** [kemie/Style-Guide-Boilerplate-Bootstrap-Edition#3]
There seems to be a slight inconsistency with the alignment of things within the `Patterns` section of the style guide. This makes it a little confusing as to how everything fits together which is kind of the point of the style guide. 

It's a little hard to explain but basically everything looks good (aligns) for the first sections of `Foundation` and `Base Styles`. The issue is with code partials within `Patterns` being nested inside a column which changes the alignment with respect to the other sections. I have used a column overlay bookmarklet which highlights the BS3 columns in order to illustrate:
![living guide pattern issue](https://cloud.githubusercontent.com/assets/146396/3879449/bc279598-2178-11e4-96da-690591b29d6d.png)

For example, in the above you can see the first `View Source` button aligns to the left of the 1st column perfectly. However within `Patterns` the button is now indented because the column has been nested. It seems to me these - as well as the headings (i.e. `Well` and `Alerts`) - should both align to the same point horizontally.

I don't really know if there is a particular reason for nesting but it does cause a slight issue when protoyping new code patterns.

**Comment by kemie** [comment]
I would guess it’s some improperly closed container divs- i’ll take a look as soon as I can

**Comment by kemie** [comment]
it took a while, but it is fixed now.
